[ClickHouse] add get catalog macros to unblock `compile --write-catalog`
* [ClickHouse] add get catalog macros to unblock `compile --write-catalog`

Closes #15896

Related to https://github.com/dbt-labs/dbt-core/issues/14585

### Problem

In ClickHouse, `dbt compile --write-catalog` now fails with:
```
[Non-critical] Issue fetching catalog for schema '.default': Failed to run macro get_catalog_relations invalid operation: Compilation Error: get_catalog_relations not implemented for clickhouse
```

### Solution

We already fixed this in `dbt-clickhouse` in this PR by @dataders : https://github.com/ClickHouse/dbt-clickhouse/pull/657.
Now this PR:
- Copies the macro from `dbt-clickhouse`
- Fixes a couple of datatype issues that arise when dealing with Arrow/ADBC

### Checklist

- [X] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me.
- [X] I have run this code in development, and it appears to resolve the stated issue.
- [X] This PR includes tests, or tests are not required or relevant for this PR.
- [X] This PR has no interface changes (e.g., macros, CLI, logs, JSON artifacts, config files, adapter interface, etc.) or this PR has already received feedback and approval from Product or DX.

Copybara-Public-Head-SHA: 31e11a2d5ca6cc35c76b262ba43914e6f6bf27f1
GitOrigin-RevId: 146bf7aea72287feff6c9acab99737fec75f31e1

* clippy

---------

Co-authored-by: Jose Muñoz <jmunozkr@gmail.com>
Co-authored-by: Felipe Oliveira Carvalho <felipekde@gmail.com>
GitOrigin-RevId: 9fd5af4440c29b9c4dce07b772c4390c8006b188